# Generated by Django 5.1 on 2024-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_created'], 'verbose_name': '', 'verbose_name_plural': 's'},
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='person',
            new_name='post',
        ),
    ]
